// Visas redaguojamas svetainės turinys. Tuščia nuoroda reiškia, kad integracija dar neįjungta.
export const content = {
  name: 'Magiškas Miškas',
  tagline: 'Gamtai miegant – bunda magija',
  description: 'Patyrimų ir šviesos spektaklis visokio ūgio vaikams po atviru dangumi.',
  city: 'Vilnius', date: 'Nuo spalio 10 d.',
  season: { mode: 'upcoming', closedMessage: 'Iki susitikimo Magiškame Miške 2027 metais!' },
  socials: { facebook: 'https://www.facebook.com/profile.php?id=61595019476553', tiktok: 'https://www.tiktok.com/@magiskasmiskas' }, contactEmail: '', reviewUrl: '',
  story: 'Kai ruduo užmigdo įprastą pasaulį, miške pradeda busti tai, ko dieną nematome: švytintys grybai, paslaptingi gyventojai, kuždantys medžiai ir istorijos, kurios atsiskleidžia tik tiems, kurie sustoja, įsiklauso ir leidžiasi vedami smalsumo. Čia pats tampi istorijos dalimi – keliauji savo taku, atrandi, palieti, išgirsti, užuodi ir patiri.',
  venue: 'VU Botanikos sodo Vingio skyrius',
  address: 'M. K. Čiurlionio g. 110, Vilnius',
  duration: 'Trukmę patikslinsime', hours: 'Darbo laiką paskelbsime netrukus',
  pause: 'Tik įžengus į mišką, jis žino – tu grįžai…',
  tickets: { url: 'https://www.bilietai.lt/renginiai/7VTPCXHIHO/magiskas-miskas-pradzia-patyrimu-spektaklis-visokio-ugio-vaikams', widgetId: 'p_s-gytq4oI1Skv9p_mYtIY1zt1HIS64XD2wUZK_W2A', iframeUrl: '', price: 'Aktualios kainos ir laisvi laikai – bilietų pasirinkime', fallbackUrl: 'https://www.bilietai.lt/' },
  appearance: { background: 'colors' },
  instagram: {
    profileUrl: 'https://www.instagram.com/magiskas.miskas/',
    endpoint: './instagram/feed.json', refreshMs: 300000, limit: 5,
  },
  map: { directionsUrl: 'https://www.google.com/maps/search/?api=1&query=VU+Botanikos+sodo+Vingio+skyrius+M.+K.+Čiurlionio+110+Vilnius', embedUrl: '' },
  journey: [
    { id: 'snabzdesiu-aleja', title: 'Šnabždesių alėja', cue: 'Įsiklausyk.', text: 'Šimtametis liepų takas, šviečiantis tūkstančiais nematytų grybų, kuždančių kerpių, knibždančių šaknų ir žėrinčių vijoklių.', detail: 'Čia prasideda tavo kelionė.' },
    { id: 'prisiminimu-kudra', title: 'Prisiminimų kūdra', cue: 'Prisimink.', text: 'Povandeninio pasaulio šviesos, šešėliai virš vandens ir vaizdiniai iš atminties: įsitaisyk ant sūpynių ir gerk pasaką iš kūdros gelmių.', detail: 'Maža pauzė dideliems jausmams.' },
    { id: 'snaudziantis-rozynas', title: 'Snaudžiantis rožynas', cue: 'Neskubėk.', text: 'Neišsigąsk dyglių, skaudžiai nedurs. Dar nemiegančios rudens rožės veda tave minčių labirintu, klausia… Ką atsakai?', detail: 'Leisk sau tiesiog būti.' },
    { id: 'paslapciu-giraite', title: 'Paslapčių giraitė', cue: 'Atrask.', text: 'Paslapčių turi visi, bet dalintis ir priimti ryžtasi tik drąsieji. Miškas priima visų paslaptis, čia dalintis ir atrasti nebaugu, čia mums saugu.', detail: 'Smalsumas žino kelią.' },
    { id: 'gardumynu-sodas', title: 'Gardumynų sodas', cue: 'Pasilik.', text: 'Nuotykiu dalintis kvies karšta arbata, blynai, pica, vegetariškas troškinys ir kai kas saldaus. Sakoma, skrandis – tai antra širdis!', detail: 'Saldžiausias kelionės taškas.' },
  ],
  practical: [
    ['Oras', 'Patyrimas vyksta po atviru dangumi. Apsirenk šiltai, pagal orą, ir rinkis patogią avalynę.'],
    ['Prieinamumas', 'Informaciją apie tako dangą, vežimėlius ir judėjimo prieinamumą patikslinsime prieš renginį.'],
  ],
  transport: [
    ['Automobiliu', 'Maršrutą planuok iki M. K. Čiurlionio g. 110, Vilniuje. Tikslią įėjimo informaciją paskelbsime prieš renginį.'],
    ['Parkavimas', 'Stovėjimo vietų ir galimų apribojimų informaciją patikslinsime. Vadovaukis vietoje esančiais ženklais.'],
    ['Viešuoju transportu', 'Aktualų maršrutą ir tvarkaraščius pasitikrink JUDU kelionių planuoklyje.', 'https://judu.lt/'],
  ],
  ticketTypes: ['Bilietas su nuolaida', 'Standartinis bilietas', 'Šeimos bilietas (3 asm.)', 'Šeimos bilietas (4 asm.)'],
  faq: [
    ['Kas yra Magiškas Miškas?', 'Tai patyrimų ir šviesos spektaklis visokio ūgio vaikams po atviru dangumi. Kelionėje laukia penkios skirtingos miško erdvės.'],
    ['Kur vyks patyrimas?', 'VU Botanikos sodo Vingio skyriuje, M. K. Čiurlionio g. 110, Vilniuje.'],
    ['Kada galima apsilankyti?', 'Magiškas Miškas bunda nuo spalio 10 d. Aktualius apsilankymo laikus rasi bilietų pasirinkime.'],
    ['Kiek trunka pasivaikščiojimas?', 'Rekomenduojamą apsilankymo trukmę patikslinsime prieš renginį.'],
    ['Ar galima atvykti su vaikų vežimėliu?', 'Tako dangos ir prieinamumo informaciją dar tiksliname. Ją paskelbsime prieš bilietų prekybos pradžią.'],
    ['Kaip įsigyti bilietą?', 'Šios svetainės bilietų skiltyje pasirink apsilankymą. Bilietų įsigijimą aptarnauja Bilietai.lt; renginį galima atidaryti ir tiesiogiai platintojo svetainėje.'],
    ['Ką daryti, jei lis?', 'Pasiruošk pasivaikščiojimui lauke. Renginio vykdymo esant nepalankiam orui ir bilietų keitimo taisykles paskelbsime kartu su bilietais.'],
    ['Ar reikia pasirinkti konkretų atvykimo laiką?', 'Pirkdamas bilietą pasirink renginio dieną ir atvykimo laiką, nurodytus Bilietai.lt.'],
    ['Ar galima ateiti su augintiniais?', 'Lankymosi su augintiniais taisykles dar tiksliname.'],
    ['Ar galima fotografuoti ir filmuoti?', 'Fotografavimo ir filmavimo taisykles paskelbsime prieš renginį.'],
    ['Ar galima atsinešti maisto ir gėrimų?', 'Atsinešamo maisto ir gėrimų taisykles dar tiksliname. Gardumynų sode lauks karšta arbata, blynai, pica, vegetariškas troškinys ir saldumynai.'],
    ['Kur galima parkuoti?', 'Stovėjimo vietų ir apribojimų informaciją paskelbsime skiltyje „Kaip atvykti“.'],
    ['Ar galima pakeisti bilieto datą arba negalint atvykti susigrąžinti pinigus?', 'Bilietų keitimo ir grąžinimo sąlygos bus pateiktos oficialiame renginio puslapyje Bilietai.lt.'],
    ['Kam kreiptis kilus problemoms dėl bilieto?', 'Dėl Bilietai.lt įsigyto bilieto kreipkis per bilietų platintojo svetainėje pateiktus pagalbos kontaktus.'],
    ['Kam taikoma nuolaida?', 'Nuolaidų gavėjų sąrašą ir reikalingus dokumentus patikslinsime prieš prekybos pradžią.'],
  ],
  final: { first: 'Miškas jau bunda.', second: 'Ar įžengsi?' },
};
